host:
  management:
    ip: 10.0.254.7
    mask: 24
  loopback:
    ip: 192.168.254.7
  uplinks:
    ge-0/0/0:
      ip: 10.2.1.1
      mask: 31
    ge-0/0/1:
      ip: 10.2.2.1
      mask: 31
  firewall_interfaces:
    ge-1/0/0:
      ip: 10.2.3.0
      mask: 31
    ge-1/0/1:
      ip: 10.2.3.2
      mask: 31
  leaf_interfaces:
    ge-2/0/0:
      ip: 10.2.3.4
      mask: 31
    ge-2/0/1:
      ip: 10.2.3.6
      mask: 31
    ge-ge-2/0/2:
      ip: 10.2.3.8
      mask: 31
    ge-2/0/3:
      ip: 10.2.3.10
      mask: 31
